Repository 1o1Project/1o1tube, pull requests merged in 2023-09, with the labels that each got.

#1 [INIT] : 초기화
  app/build.gradle
  app/src/main/java/com/example/loltube/data/RetrofitInstance.kt
  app/src/main/java/com/example/loltube/data/YoutubeApiService.kt
  app/src/main/java/com/example/loltube/model/YoutubeChannelInfo.kt
  app/src/main/java/com/example/loltube/model/YoutubeVideo.kt
  app/src/main/java/com/example/loltube/model/YoutubeVideoInfo.kt
  app/src/main/java/com/example/loltube/ui/activity/MainActivity.kt
  app/src/main/java/com/example/loltube/util/Constants.kt
  app/src/main/java/com/example/loltube/util/Utils.kt
Labels: init

#2 [LAYOUT] : HomeFragment
  .idea/.name
  .idea/gradle.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/java/com/example/loltube/ui/activity/MainActivity.kt
  app/src/main/java/com/example/loltube/ui/adapter/HomeAdapter.kt
  app/src/main/java/com/example/loltube/ui/adapter/ViewPagerFragmentAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeModel.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeViewModel.kt
  app/src/main/java/com/example/loltube/ui/fragment/HomeFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/MainFragment.kt
  app/src/main/java/com/example/loltube/util/Constants.kt
  app/src/main/res/drawable/ic_1o1_logo.png
  app/src/main/res/drawable/ic_home.png
  app/src/main/res/drawable/ic_my_page.png
  app/src/main/res/drawable/ic_search.png
  app/src/main/res/font/beaufortforlol_bold.ttf
  app/src/main/res/font/beaufortforlol_heavy.ttf
  app/src/main/res/font/beaufortforlol_medium.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/home_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: layout

#7 [DESIGN] : detailfragment
  app/src/main/res/drawable/ic_leftarrow.png
  app/src/main/res/drawable/lol_thumbnail.png
  app/src/main/res/layout/fragment_video_detail.xml
Labels: layout

#8 [FEATURE] : HomeFragment 클릭 기능 추가
  app/src/main/java/com/example/loltube/ui/adapter/HomeAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeViewModel.kt
  app/src/main/java/com/example/loltube/ui/fragment/MainFragment.kt
  app/src/main/java/com/example/loltube/util/Constants.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/spinner_item.xml
Labels: feature

#9 [FEATURE] : SharedPreferences 추가
  app/src/main/java/com/example/loltube/data/SharedPrefInstance.kt
  app/src/main/java/com/example/loltube/ui/fragment/MyVideoFragment.kt
  app/src/main/res/layout/favorite_item.xml
  app/src/main/res/layout/fragment_my_video.xml
Labels: enhancement

#10 [FEAT] : SearchFragment API
  .idea/gradle.xml
  app/src/main/java/com/example/loltube/ui/fragment/SearchFragment.kt
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_item.xml
Labels: feature

#12 [PACK] : 🎁 리팩토링
  app/src/main/java/com/example/loltube/data/SharedPrefInstance.kt
  app/src/main/java/com/example/loltube/model/LOLModel.kt
  app/src/main/java/com/example/loltube/ui/adapter/HomeAdapter.kt
  app/src/main/java/com/example/loltube/ui/adapter/SearchAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeViewModel.kt
  app/src/main/java/com/example/loltube/ui/fragment/SearchFragment.kt
Labels: refactoring

#13 [검색] : 클릭 시 이동
  .idea/vcs.xml
  app/src/main/java/com/example/loltube/ui/adapter/SearchAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/SearchFragment.kt
  app/src/main/java/com/example/loltube/util/Constants.kt
Labels: enhancement, feature

#14 [Home] : 레이아웃 완성
  app/build.gradle
  app/src/main/java/com/example/loltube/ui/adapter/HomeAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeViewModel.kt
  app/src/main/java/com/example/loltube/ui/fragment/VideoDetailFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_item.xml
  app/src/main/res/values/spinner_item.xml
  app/src/main/res/values/strings.xml
Labels: layout

#15 [MYPAGE] : 디자인 추가
  app/src/main/java/com/example/loltube/ui/fragment/MyVideoFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/VideoDetailFragment.kt
Labels: layout

#16 [디테일] : 상세정보 띄우기
  .idea/.name
  app/src/main/java/com/example/loltube/model/LOLModel.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/SearchFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/VideoDetailFragment.kt
  app/src/main/res/layout/fragment_video_detail.xml
  build.gradle
Labels: enhancement, feature

#18 [HOME] : 홈 어댑터 수정
  app/src/main/java/com/example/loltube/ui/adapter/HomeCategoryAdapter.kt
  app/src/main/java/com/example/loltube/ui/adapter/HomeChannelAdapter.kt
  app/src/main/java/com/example/loltube/ui/adapter/HomePopularAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeFragment.kt
  app/src/main/java/com/example/loltube/util/Constants.kt
Labels: refactoring

#19 [SHORTS] : 쇼츠 영상목록 구현
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/loltube/data/ShortsRepository.kt
  app/src/main/java/com/example/loltube/data/ShortsRepositoryImpl.kt
  app/src/main/java/com/example/loltube/ui/adapter/ShortsListAdapter.kt
  app/src/main/java/com/example/loltube/ui/adapter/ViewPagerFragmentAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/MainFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/MyVideoFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/ShortsFragment.kt
  app/src/main/java/com/example/loltube/ui/viewmodel/ShortsViewModel.kt
  app/src/main/java/com/example/loltube/ui/viewmodel/ShortsViewModelFactory.kt
  app/src/main/java/com/example/loltube/util/Constants.kt
  app/src/main/res/layout/fragment_shorts.xml
  app/src/main/res/layout/shorts_item.xml
  build.gradle
Labels: enhancement

#20 [HOME] : 홈화면 추가과제 완료
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/loltube/data/YoutubeApiService.kt
  app/src/main/java/com/example/loltube/model/YoutubeVideoInfo.kt
  app/src/main/java/com/example/loltube/ui/activity/MainActivity.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeViewModel.kt
  app/src/main/java/com/example/loltube/ui/fragment/MainFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/SearchFragment.kt
  app/src/main/java/com/example/loltube/util/Constants.kt
  app/src/main/res/drawable/ic_person.png
  app/src/main/res/font/beaufortforlol_kr_bold.ttf
  app/src/main/res/font/lee_sun_sin_bold.ttf
  app/src/main/res/font/yanolja_bold.ttf
  app/src/main/res/font/yanolja_regular.ttf
  app/src/main/res/layout/favorite_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_item.xml
  app/src/main/res/layout/home_item2.xml
  app/src/main/res/values/colors.xml
  build.gradle
Labels: feature

#21 [DETAIL] : 디테일,myvideo기능 구현
  .idea/.name
  .idea/misc.xml
  app/src/main/java/com/example/loltube/data/SharedPrefInstance.kt
  app/src/main/java/com/example/loltube/model/LOLModel.kt
  app/src/main/java/com/example/loltube/ui/adapter/FavoriteListAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/MyVideoFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/SearchFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/VideoDetailFragment.kt
  app/src/main/java/com/example/loltube/util/Constants.kt
  app/src/main/res/layout/fragment_video_detail.xml
  build.gradle
Labels: feature

#22 [SHORTS] : 영상재생 관련 버그 해결
  app/src/main/java/com/example/loltube/ui/adapter/ShortsListAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/ShortsFragment.kt
Labels: enhancement
