Repository 1o1Project/1o1tube, pull requests merged in 2023-10, with the labels that each got.

#23 Feature/homefragment
  app/src/main/java/com/example/loltube/data/YoutubeApiService.kt
  app/src/main/java/com/example/loltube/model/YoutubeChannelInfo.kt
  app/src/main/java/com/example/loltube/model/YoutubeVideo.kt
  app/src/main/java/com/example/loltube/model/YoutubeVideoInfo.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/Home/HomeViewModel.kt
  app/src/main/java/com/example/loltube/util/Constants.kt
  app/src/main/res/font/yanolja_bold.ttf
  app/src/main/res/font/yanolja_regular.ttf
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_item.xml
  app/src/main/res/layout/home_item2.xml
Labels: refactoring

#25 [SEARCH] : 충돌해결 완료
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  app/src/main/java/com/example/loltube/ui/adapter/SearchAdapter.kt
  app/src/main/java/com/example/loltube/ui/adapter/ShortsListAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/SearchFragment.kt
  app/src/main/java/com/example/loltube/ui/fragment/ShortsFragment.kt
  app/src/main/java/com/example/loltube/util/Constants.kt
  app/src/main/res/drawable/ic_downloading.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_item.xml
Labels: fix

#26 [MYVIDEO] : 뷰모델 구현
  app/src/main/java/com/example/loltube/data/ShortsRepositoryImpl.kt
  app/src/main/java/com/example/loltube/ui/adapter/FavoriteListAdapter.kt
  app/src/main/java/com/example/loltube/ui/adapter/ShortsListAdapter.kt
  app/src/main/java/com/example/loltube/ui/fragment/MyVideoFragment.kt
  app/src/main/java/com/example/loltube/ui/viewmodel/MyVideoViewModel.kt
Labels: enhancement
